[Bug]: fix runtime path
LunarVim/LunarVim pull request #1443
Opened 2021-09-01 09:09 UTC by aaronsms

# Description

Please include a summary of the change and which issue is fixed. \
List any dependencies that are required for this change.

Fixes #1442

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. \
Provide instructions so we can reproduce. \
Please also list any relevant details for your test configuration.

- Run command `set rtp?` and `set packpath?`
- Results shows that */after paths indeed comes after paths without.
- Testing on a user plugin "vimtex" now loads correctly.

2021-09-01 10:02 UTC, kylo252 commented
So the problem is basically solved by using `prepend` instead of `append` for the "after" directory.

But why are you mixing up the removal, or the operations, order in general?

It's easier to maintain and reason about which directory replaces which when they are in order. e,g. fix the "config" ones first and then fix the "data" directories.

2021-09-01 10:05 UTC, kylo252 requested changes
As I mentioned, it's easier to track if the "listing order" of the modifications is maintained as we have it right now. 
Readability takes precedence over removing a few extra of calls in this case for me.

2021-09-02 14:04 UTC, aaronsms commented
> So the problem is basically solved by using `prepend` instead of `append` for the "after" directory.
> 
> But why are you mixing up the removal, or the operations, order in general?
> 
> It's easier to maintain and reason about which directory replaces which when they are in order. e,g. fix the "config" ones first and then fix the "data" directories.
> 

ok fair enough, but the "data" directories changes would have to come before "config" ones to preserve the following order.

1. config 
2. data
3. data (after)
4. config (after)

2021-09-02 15:23 UTC, kylo252 approved these changes

2021-09-02 15:29 UTC, merged