fix(lualine): load onedarker theme
LunarVim/LunarVim pull request #1909
Opened 2021-11-05 17:41 UTC by younger-1

# Description

Move `onedarker` theme from `lua/lvim/lualine/themes/onedarker.lua` to `lua/lualine/themes/onedarker.lua` 
If do not specify `lvim.builtin.lualine.options.theme`, it will defaults to `auto` other than `onedarker` which is set here:

https://github.com/LunarVim/LunarVim/blob/adc0b8b4642508408f6aedb7937ec0fdc2a891d8/lua/lvim/core/lualine/styles.lua#L130-L132

## How Has This Been Tested?

Before:
```lua
print(lvim.builtin.lualine.options.theme)   -- 'auto'
```

After:
```lua
print(lvim.builtin.lualine.options.theme)   -- 'onedarker'
```

2021-11-06 07:56 UTC, kylo252 commented
I think something wrong happened during your branch merge/update, because the description covers changes that aren't currently present in the PR.

2021-11-06 08:28 UTC, younger-1 commented
The code above is to show where `lvim.builtin.lualine.options.theme` got value.
I just moved the `onedarker` file to proper place where `lualine` could find the theme and change the `fg` of section `a`
Because the previous change had been merged to rolling branch in [this commit](https://github.com/LunarVim/LunarVim/commit/ebb622539831bddd14776433f0ad8ec939a166ac) by ChristianChiarulli, so I have to resolved conflict by merging rolling branch again.

2021-11-16 09:49 UTC, kylo252 requested changes
You also need the same changes for other modes
```diff
diff --git a/lua/lualine/themes/onedarker.lua b/lua/lualine/themes/onedarker.lua
index 396657b..f63fd35 100644
--- a/lua/lualine/themes/onedarker.lua
+++ b/lua/lualine/themes/onedarker.lua
@@ -19,13 +19,13 @@ local colors = {
 -- LuaFormatter on
 return {
   normal = {
-    a = { fg = colors.fg, bg = colors.blue, gui = "bold" },
+    a = { fg = colors.gray2, bg = colors.blue, gui = "bold" },
     b = { fg = colors.fg, bg = colors.bg },
     c = { fg = colors.fg, bg = colors.bg },
   },
-  insert = { a = { fg = colors.fg, bg = colors.green, gui = "bold" } },
-  visual = { a = { fg = colors.fg, bg = colors.purple, gui = "bold" } },
-  command = { a = { fg = colors.fg, bg = colors.yellow, gui = "bold" } },
+  insert = { a = { fg = colors.gray2, bg = colors.green, gui = "bold" } },
+  visual = { a = { fg = colors.gray2, bg = colors.purple, gui = "bold" } },
+  command = { a = { fg = colors.gray2, bg = colors.yellow, gui = "bold" } },
   replace = { a = { fg = colors.fg, bg = colors.red1, gui = "bold" } },
   inactive = {
     a = { fg = colors.gray1, bg = colors.bg, gui = "bold" },

```

2021-11-16 09:49 UTC, kylo252 commented on lua/lualine/themes/onedarker.lua
> +    a = { fg = colors.bg, bg = colors.blue, gui = "bold" },
```suggestion
    a = { fg = colors.gray2, bg = colors.blue, gui = "bold" },
```

2021-11-16 17:48 UTC, kylo252 approved these changes
Thank you!

2021-11-16 17:49 UTC, merged