chore(plugins): restore the base folke/lua-dev
LunarVim/LunarVim pull request #2193
Opened 2022-01-18 15:57 UTC by kylo252

# Description

Restore the original base folke/lua-dev.nvim

--- 

Note: an interesting commit https://github.com/hrsh7th/nvim-cmp/commit/8fc8d31cf451b8becb39087aa2190bee29a8b009

2022-01-18 15:58 UTC, kylo252 commented
@abzcoding, we can probably wait with this until tomorrow in case there are more updates.

2022-01-18 16:09 UTC, abzcoding approved these changes
I agree. We probably should wait a bit.

2022-01-18 21:52 UTC, abzcoding requested changes

2022-01-18 21:52 UTC, abzcoding commented on lua/lvim/plugins.lua
> +  nvim_treesitter = "8b1d3906199e1572c2201e494bba017d823c0c8f",
btw this causes weird issues for neovim head. Can we keep nvim_treesitter for another PR to make sure it doesn't break anything

2022-01-18 22:01 UTC, abzcoding commented
@kylo252 can we keep treesitter before https://github.com/nvim-treesitter/nvim-treesitter/commit/c80715f883b8c7963782973b23297c5dec7924be

it causes all sorts of errors atm in neovim head

2022-01-18 22:05 UTC, abzcoding commented
<img width="1911" alt="Screen Shot 2022-01-19 at 1 35 17 AM" src="https://user-images.githubusercontent.com/10992695/150026178-58f1cbe1-828f-4c48-8890-2f2fef6cd220.png">

2022-01-19 08:14 UTC, abzcoding commented
we can probably run the `make generate_plugins_sha` one more time, before merging this, to make sure we are adding all the changes :)

2022-01-19 08:19 UTC, kylo252 commented
> we can probably run the `make generate_plugins_sha` one more time, before merging this, to make sure we are adding all the changes :)

Another treesitter commit 👀

2022-01-19 08:21 UTC, abzcoding commented
LGTM 🚀

2022-01-19 08:23 UTC, merged

2022-01-19 08:26 UTC, abzcoding commented
we should somehow remind users to do a `:TSUpdate` as well 🤔

2022-01-19 08:40 UTC, kylo252 commented
> we should somehow remind users to do a `:TSUpdate` as well thinking

I was going to write the same thing, but I forgot that It's not needed if you're running `:LvimUpdate` :sweat_smile: 

https://github.com/LunarVim/LunarVim/blob/56df185b1b9ec9c620e80654d314541beca76f26/lua/lvim/utils/hooks.lua#L45-L61