fix(code-lens): make sure we are using code_lens correctly
LunarVim/LunarVim pull request #2576
Opened 2022-05-05 21:18 UTC by abzcoding

# Description
what the title says

Fixes #2574

2022-05-05 21:18 UTC, abzcoding commented
@cladera can you test this out?

2022-05-06 06:00 UTC, cladera requested changes

2022-05-06 08:46 UTC, abzcoding commented on lua/lvim/lsp/utils.lua
>  end
that makes sense 👍

2022-05-06 09:27 UTC, cladera commented on lua/lvim/lsp/utils.lua
> +    end,
I was going to suggest the same

2022-05-06 09:35 UTC, kylo252 approved these changes
LGTM! 🚀

2022-05-06 09:42 UTC, merged