doc: Update README
LunarVim/LunarVim pull request #3234
Opened 2022-10-14 07:11 UTC by epilande

# Description

The README is a bit confusing...

<img width="814" alt="image" src="https://user-images.githubusercontent.com/3210082/195784515-1e2b7a35-55eb-46c7-b29f-8f7329baa606.png">

This PR updates the README to match installation docs – https://www.lunarvim.org/docs/installation#nightly

2022-10-16 06:33 UTC, kylo252 requested changes

2022-10-16 06:33 UTC, kylo252 commented on README.md
> +If you are running Neovim 0.9+
```suggestion
If you are running Neovim nightly 
```

2022-10-16 07:30 UTC, ChristianChiarulli commented
https://github.com/LunarVim/LunarVim/issues/3253 this issues should be handled before worrying about documentation

2022-11-11 13:19 UTC, gnmearacaun commented
Rolling branch is depreciated

2022-11-11 13:19 UTC, closed without merging