feat(alpha): adding option to turn off ESC keybind to exit
LunarVim/LunarVim pull request #3767
Opened 2023-01-22 12:38 UTC by anchal270899

# Description

Added option to modify the autocommand that declares <ESC> as :qa when in filetype=alpha 
Added default as true to alpha.lua's main config, to not have any change to the current settings. 
Added "q to exit" to the alpha (dashboard mode) prompt list to make the q to :qa\<CR\> remap apparent.

## How Has This Been Tested?

- Tested with and without newly added setting `lvim.builtin.alpha.esc_to_quit = true/false` to only change the action if setting is added to personal config.

2023-01-23 08:16 UTC, LostNeophyte requested changes
Can you remove the autocmd change and leave the "q to exit" one?

I plan to make all autocommands configurable in the future, I need to figure out the best way to do it, but I think that putting options in `lvim.builtin.plugin` will be problematic

for now you can use 
`vim.api.nvim_clear_autocmds { pattern = "alpha", group = "_filetype_settings" }`
to remove that autocomand

2023-01-23 16:24 UTC, pr-313 commented on lua/lvim/core/alpha.lua
> +    esc_to_quit = true,
```suggestion
```

2023-01-23 16:24 UTC, pr-313 commented on lua/lvim/core/autocmds.lua
> +            vim.cmd [[
```suggestion
          vim.cmd [[
            set nobuflisted
            nnoremap <silent> <buffer> q :qa<CR>
```

2023-01-26 12:44 UTC, LostNeophyte commented on lua/lvim/core/autocmds.lua
> +          end
```suggestion
```

that's a syntax error

2023-01-26 12:44 UTC, LostNeophyte commented on lua/lvim/core/autocmds.lua
>              nnoremap <silent> <buffer> q :qa<CR>
```suggestion
```

you already added it as a button

2023-01-26 15:13 UTC, LostNeophyte commented on lua/lvim/core/autocmds.lua
> +            nnoremap <silent> <buffer> <esc> :qa<CR>
let's just get rid of ESC
```suggestion
```

2023-01-26 15:19 UTC, LostNeophyte approved these changes
Thanks!

I removed the ESC keybind completely, it's not that intuitive and `q` is enough

2023-01-26 15:20 UTC, merged