feat(plugin): add rounded borders to :LspInfo window
LunarVim/LunarVim pull request #4208
Opened 2023-05-27 11:40 UTC by sadikeey

# Description
Added rounded borders to `:LspInfo` window to make LunarVim experience more cohesive.

## How Has This Been Tested?
`:LspInfo`

## Screenshot
![Screenshot_2023-05-27_16:54:25](https://github.com/LunarVim/LunarVim/assets/86684667/9fd1e343-cde1-429f-98cd-2232cfcc0e06)

2023-05-29 04:35 UTC, cpea2506 requested changes

2023-05-29 04:35 UTC, cpea2506 commented on lua/lvim/lsp/init.lua
> +  end)
```suggestion
   require("lspconfig.ui.windows").default_options.border = "rounded"
```
I think if `lspconfig` is loaded succesfully at this line below then we are ok without `pcall`
https://github.com/LunarVim/LunarVim/blob/7b413c428501b93e71e0342ae6d21c2b632c34ac/lua/lvim/lsp/init.lua#L92

2023-05-29 19:32 UTC, LostNeophyte approved these changes

2023-05-30 05:10 UTC, cpea2506 approved these changes

2023-06-03 08:49 UTC, LostNeophyte commented
Thanks!

2023-06-03 08:49 UTC, merged