[feat] Added bun as an npm package manager
LunarVim/LunarVim pull request #4362
Opened 2023-09-11 02:17 UTC by TheBearodactyl

# Description

I have added `bun` as a possible `npm` package manager in the install script, and have also prioritized it before `yarn` as a package manager because of the MASSIVE performance increase. 

I have made the output of the `JS` dependency installation prompt use "`NodeJS/BunJS`" instead of `NodeJS` as `BunJS` is independent from `NodeJS`

Along with the output of the `JS` dependency installation prompt, if it uses `bun` as the package manager, it replaces `NodeJS` with `BunJS`

## How Has This Been Tested?

I have run the script both locally and from my forked repo with and without bun installed.

2023-09-30 09:21 UTC, cpea2506 approved these changes

2024-01-12 17:58 UTC, Haeven approved these changes
LGTM 😄 Nice addition!

2024-01-12 18:41 UTC, TheBearodactyl commented
> LGTM 😄 Nice addition!

:D

2024-01-12 18:44 UTC, TheBearodactyl commented
![2024-01-12_12-44](https://github.com/LunarVim/LunarVim/assets/114454115/468b1b5e-fd16-4052-be2b-90c763e2f3a9)
the fuck.

2024-01-12 23:37 UTC, LostNeophyte commented
lsp template tests don't always work well, you can ignore it

2024-01-12 23:41 UTC, LostNeophyte requested changes

2024-01-12 23:41 UTC, LostNeophyte commented on utils/installer/install.sh
> +    manager_home="$(echo "$BUN_INSTALL" 2>/dev/null)"
any reason this can't be just this?
```suggestion
    manager_home="$BUN_INSTALL"
```

2024-01-13 20:46 UTC, TheBearodactyl commented
> lsp template tests don't always work well, you can ignore it

ah

2024-01-13 20:46 UTC, TheBearodactyl commented on utils/installer/install.sh
> +    manager_home="$(echo "$BUN_INSTALL" 2>/dev/null)"
good point

2024-01-13 21:32 UTC, LostNeophyte approved these changes
LGTM, thanks!

2024-01-13 21:33 UTC, merged